### PR TITLE
fix cleared on Bar click bug (Single click event)

### PR DESCRIPTION
**Pull request by nappannda**

### CODE REVIEW

**Comment by ome450901** [comment]
Hello, I'm wondering what is this bug and how to reproduce, thanks!

**Comment by nappannda** [comment]
Hello! 
As a detail of bug, such a thing happened.
Position clicked with "ACTION_UP" and "mRating" were compared, when the position clicked on "mRating" at "ACTION_MOVE" was saved.
Because of that, clearRating-functions were called and program was initialized.

To fix the bug, I put the clicked position before into “previewRating”, a variable to fix the problem that it couldn’t make comparison between “mRating” and “rating” with "SingleClickEvent" in "ACTION_UP".

**Comment by nappannda** [comment]
screenrecord_2017-05-20-21-30-39

**Comment by ome450901** [comment]
I was been busy recently, sorry for reply so late!
I don't know why that I can't reproduce this bug, but I think maybe is the `Single Click Event` determination cause this bug.

What do you think if we change the determination of Single Click event from `duration` to `position` of the x axis and the y axis?

I think maybe this way will be better than add a parameter to save previous rating, but I can't reproduce the bug so I can't do some tests.

**Comment by nappannda** [comment]
This bug is that "clearRating" is called by single click.
The reason is that "mRating" is updated with "ACTION_MOVE" and it is judged on single click based on the value.
So, I think that changing the judgment of single click will not be a fundamental solution.

**Comment by ome450901** [comment]
But when ACTION_MOVE triggered, the Single click event in ACTION_UP suppose will not be executed, right?
because this line of code `if (duration < MAX_CLICK_DURATION)` is not true.

I'm sorry that I can't understand why this bug happened, in my emulator everything seems corrected.

ezgif com-video-to-gif

**Comment by nappannda** [comment]
Umm…
I found that this bug arised in my own real machine, but I could not reproduce it in the emulator.
What could I do for this Pull Request?

**Comment by ome450901** [comment]
I will merge this pull request first to solve this bug, and maybe I will find another way to improve touch event processing.
Anyway, thanks for helping me to figure out the bug!

**Pull request merged**
